# config/packages/acseo_typesense.yml
acseo_typesense:
  # Typesense host settings
  typesense:
    url: '%env(resolve:TYPESENSE_URL)%'
    key: '%env(resolve:TYPESENSE_KEY)%'
    collection_prefix: 'test_'                 # Optional : add prefix to all collection
    #            names in Typesense
  # Collection settings
  collections:
    contacts: # Typesense collection name
      entity: 'Celtic34fr\ContactGestion\Entity\Contacts'              # Doctrine Entity class
      fields:
        #
        # Keeping Database and Typesense synchronized with ids
        #
        id: # Entity attribute name
          name: id                       # Typesense attribute name
          type: primary                  # Attribute type
        #
        # Using again id as a sortable field (int32 required)
        #
        sortable_id:
          entity_attribute: id             # Entity attribute name forced
          name: sortable_id                # Typesense field name
          type: int32
        sujet:
          name: sujet
          type: string
        demande:
          name: demande
          type: object                    # Object conversion with __toString()
        publishedAt:
          name: created_at
          type: datetime
          optional: true                   # Declare field as optional
        treated_at:
          name: treated_at
          type: datetime
          optional: true                   # Declare field as optional
      default_sorting_field: sortable_id       # Default sorting field. Must be int32 or float
      symbols_to_index: [ '+' ]                  # Optional - You can add + to this list to make the word c++ indexable verbatim.
      finders:                                 # Declare your specific finder
        contacts_autocomplete:                  # Finder name
          finder_parameters:               # Parameters used by the finder
            query_by: demande              #
            limit: 10                    # You can add as key / valuesspecifications
            prefix: true                 # based on Typesense Request
            num_typos: 1                 #
            drop_tokens_threshold: 1     #