# Reference extension configuration file

coordonnees:
  visu: true

adresse:
  adresse: 'address'
  complement: 'more informations'
  code-post: 'french zip code'
  ville: 'town'

OSM:
  container: 'carte'
  width: '100%'
  height: '400px'
  lat: your latitude'
  long: 'your longitude'
  zoom: 17
  zoomMax: 20
  zoomMin: 1
  visu: true

newsletter:
  visu: true

contact_form_template: contact-gestion/contact/formulaire.html.twig

redirect_after_record: homepage
