# Reference extension configuration file

coordonnees:
  tel: '+33-7-82-65-90-35 (07-82-65-90-35)'
  courriel: 'deveze.services@gmail.com'
  visu: true

adresse:
  adresse: '9, rue des Spahis'
  complement: ''
  code-post: '34500'
  ville: 'Béziers, Occitanie, France'

OSM:
  container: 'carte'
  width: '100%'
  height: '400px'
  lat: 43.341265
  long: 3.252433
  zoom: 17
  zoomMax: 20
  zoomMin: 1
  visu: true

newsletter:
  visu: true

contact_form_template: contact-gestion/contact/formulaire.html.twig

redirect_after_record: homepage
