contact:
  path: /contact
  controller: Bolt\Extension\Celtic34fr\ContactGestion\Controller\ContactController

reference_extension:
  resource: '../../vendor/celtic34fr/contact-gestion/src/Controller/Backend/'
  prefix: '%bolt.backend_url%'
  type: annotation