contact:
  path: /contact
  controller: Celtic34fr\ContactGestion\Controller\ContactController

reference_extension:
  resource: '../../vendor/celtic34fr/contact-gestion/src/Controller/'
  prefix: '%bolt.backend_url%'
  type: annotation