# An example of a services.yaml file in an extension

doctrine:
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      Contact_Gestion:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/vendor/celtic34fr/contact-gestion/src/Entity'
        prefix: 'Celtic34fr\ContactGestion'
        alias: ContactGestion

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Celtic34fr\ContactGestion\AdminMenu:
    class: Celtic34fr\ContactGestion\AdminMenu
    arguments: [ '@Symfony\Component\Routing\Generator\UrlGeneratorInterface' ]
    tags: [ 'bolt.extension_backend_menu' ]

  Celtic34fr\ContactGestion\Widget\ContactsWidget:
    autowire: true

  Celtic34fr\ContactGestion\Controller\Backend\SearchController:
    arguments:
      $autocompleteContactFinder: '@typesense.finder'
